import prism from 'prismjs'

import 'prismjs-components-importer/cjs/prism-c'
import 'prismjs-components-importer/cjs/prism-clojure'
import 'prismjs-components-importer/cjs/prism-cpp'
import 'prismjs-components-importer/cjs/prism-csharp'
import 'prismjs-components-importer/cjs/prism-css'
import 'prismjs-components-importer/cjs/prism-dart'
import 'prismjs-components-importer/cjs/prism-docker'
import 'prismjs-components-importer/cjs/prism-elixir'
import 'prismjs-components-importer/cjs/prism-go'
import 'prismjs-components-importer/cjs/prism-markup'
import 'prismjs-components-importer/cjs/prism-java'
import 'prismjs-components-importer/cjs/prism-javascript'
import 'prismjs-components-importer/cjs/prism-json'
import 'prismjs-components-importer/cjs/prism-julia'
import 'prismjs-components-importer/cjs/prism-kotlin'
import 'prismjs-components-importer/cjs/prism-lua'
import 'prismjs-components-importer/cjs/prism-markdown'
import 'prismjs-components-importer/cjs/prism-pascal'
import 'prismjs-components-importer/cjs/prism-php'
import 'prismjs-components-importer/cjs/prism-python'
import 'prismjs-components-importer/cjs/prism-ruby'
import 'prismjs-components-importer/cjs/prism-rust'
import 'prismjs-components-importer/cjs/prism-sql'
import 'prismjs-components-importer/cjs/prism-typescript'
import 'prismjs-components-importer/cjs/prism-yaml'

export default prism
